[build]
  command = "npm run build"
  publish = "client/dist"

# Handle routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment settings
[build.environment]
  NODE_VERSION = "18.x"
  VITE_FIREBASE_API_KEY = "dummy-api-key"
  VITE_FIREBASE_AUTH_DOMAIN = "dummy-project.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "dummy-project"
  VITE_FIREBASE_STORAGE_BUCKET = "dummy-project.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "123456789"
  VITE_FIREBASE_APP_ID = "1:123456789:web:abcdef123456"
  VITE_FIREBASE_MEASUREMENT_ID = "G-ABCDEFGHI"
  VITE_API_URL = "/api"
  VITE_STORAGE_URL = "/storage"
  VITE_APP_NAME = "Professional Portfolio"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; img-src 'self' https: data: blob:; media-src 'self' https: data: blob:;" 