// Re-export all page components for easier imports
export { default as Home } from './Home';
export { default as About } from './About';
export { default as Portfolio } from './Portfolio';
export { default as Experience } from './Experience';
export { default as Press } from './Press';
export { default as Contact } from './Contact';
export { default as Blog } from './Blog';
export { default as Admin } from './Admin';
export { default as NotFound } from './NotFound'; 